// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMfGiXTHBTQ6nHOYm38Hyl2PM6iOA8LQ',
    appId: '1:57875758213:web:b55a8c505ecdbc6e97bdec',
    messagingSenderId: '57875758213',
    projectId: 'stocklite-92a17',
    authDomain: 'stocklite-92a17.firebaseapp.com',
    storageBucket: 'stocklite-92a17.firebasestorage.app',
    measurementId: 'G-GR487DSMQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4VkZHWPGojfutv8YrKtGfNKCetuQ0Cg',
    appId: '1:57875758213:android:ad94e1a9af8d5fd797bdec',
    messagingSenderId: '57875758213',
    projectId: 'stocklite-92a17',
    storageBucket: 'stocklite-92a17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TDXsnq0BIDA9rSnZnUIs_21XzoAn-58',
    appId: '1:57875758213:ios:0b003609093f693a97bdec',
    messagingSenderId: '57875758213',
    projectId: 'stocklite-92a17',
    storageBucket: 'stocklite-92a17.firebasestorage.app',
    iosBundleId: 'com.example.stockliteApp',
  );
}
